var searchData=
[
  ['elf_20files_0',['Step 2: Load ELF Files',['../manual.html#autotoc_md27',1,'']]],
  ['elf32_5fehdr_1',['Elf32_Ehdr',['../structlibmicroemu_1_1internal_1_1_elf32___ehdr.html',1,'libmicroemu::internal']]],
  ['elf32_5fphdr_2',['Elf32_Phdr',['../structlibmicroemu_1_1internal_1_1_elf32___phdr.html',1,'libmicroemu::internal']]],
  ['elfreader_3',['ElfReader',['../classlibmicroemu_1_1internal_1_1_elf_reader.html',1,'libmicroemu::internal']]],
  ['embedding_20considerations_4',['Embedding Considerations',['../index.html#autotoc_md10',1,'']]],
  ['embedding_20libmicroemu_20in_20your_20project_5',['Embedding libmicroemu in Your Project',['../index.html#autotoc_md8',1,'']]],
  ['emucontext_6',['EmuContext',['../classlibmicroemu_1_1_emu_context.html',1,'libmicroemu']]],
  ['emulation_7',['Step 3: Start Emulation',['../manual.html#autotoc_md28',1,'']]],
  ['emulator_8',['Emulator',['../classlibmicroemu_1_1internal_1_1_emulator.html',1,'libmicroemu::internal::Emulator&lt; TCpuStates &gt;'],['../index.html#autotoc_md6',1,'Running the Emulator']]],
  ['emulator_20library_9',['ARM Microcontroller Emulator Library',['../index.html',1,'']]],
  ['eor1immcarryop_10',['Eor1ImmCarryOp',['../classlibmicroemu_1_1internal_1_1_eor1_imm_carry_op.html',1,'libmicroemu::internal']]],
  ['eor2shiftop_11',['Eor2ShiftOp',['../classlibmicroemu_1_1internal_1_1_eor2_shift_op.html',1,'libmicroemu::internal']]],
  ['epsrregister_12',['EpsrRegister',['../structlibmicroemu_1_1_epsr_register.html',1,'libmicroemu']]],
  ['error_20management_13',['Error Management',['../manual.html#autotoc_md19',1,'']]],
  ['evaluatestate_14',['EvaluateState',['../classlibmicroemu_1_1_machine.html#af0d65ffa178a42f9a119bba280284446',1,'libmicroemu::Machine']]],
  ['example_20code_15',['Example Code',['../manual.html#autotoc_md25',1,'']]],
  ['example_3a_20integrating_20libmicroemu_16',['Example: Integrating libmicroemu',['../index.html#autotoc_md9',1,'']]],
  ['exceptioncontext_17',['ExceptionContext',['../structlibmicroemu_1_1internal_1_1_exception_context.html',1,'libmicroemu::internal']]],
  ['exceptionpostexecution_18',['ExceptionPostExecution',['../classlibmicroemu_1_1internal_1_1_exception_post_execution.html',1,'libmicroemu::internal']]],
  ['exceptionpostfetch_19',['ExceptionPostFetch',['../classlibmicroemu_1_1internal_1_1_exception_post_fetch.html',1,'libmicroemu::internal']]],
  ['exceptionprefetch_20',['ExceptionPreFetch',['../classlibmicroemu_1_1internal_1_1_exception_pre_fetch.html',1,'libmicroemu::internal']]],
  ['exceptionsops_21',['ExceptionsOps',['../classlibmicroemu_1_1internal_1_1_exceptions_ops.html',1,'libmicroemu::internal']]],
  ['exceptionstates_22',['ExceptionStates',['../structlibmicroemu_1_1_exception_states.html',1,'libmicroemu']]],
  ['exceptiontype_23',['ExceptionType',['../namespacelibmicroemu.html#a59fde2619e3c9f661be510ea9229c0e1',1,'libmicroemu']]],
  ['exec_24',['Exec',['../classlibmicroemu_1_1_machine.html#a7f302218280c95778710a790296b9514',1,'libmicroemu::Machine']]],
  ['exec_5fresult_2eh_25',['exec_result.h',['../exec__result_8h.html',1,'']]],
  ['execresult_26',['ExecResult',['../classlibmicroemu_1_1_exec_result.html',1,'libmicroemu::ExecResult'],['../classlibmicroemu_1_1_exec_result.html#ae2f80c6049631355adc31d0143e20709',1,'libmicroemu::ExecResult::ExecResult(StatusCode status_code, int program_exit_code) noexcept'],['../classlibmicroemu_1_1_exec_result.html#a8ed6df50ce766fed66a118d47e84795d',1,'libmicroemu::ExecResult::ExecResult(ExecResult &amp;&amp;r) noexcept=default'],['../classlibmicroemu_1_1_exec_result.html#a4c3abd7a35c790e2149b659cad1bfbff',1,'libmicroemu::ExecResult::ExecResult(const ExecResult &amp;r) noexcept=default']]],
  ['executor_27',['Executor',['../classlibmicroemu_1_1internal_1_1_executor.html',1,'libmicroemu::internal']]],
  ['extensibility_28',['Extensibility',['../manual.html#autotoc_md29',1,'']]],
  ['extractbits1r_29',['ExtractBits1R',['../classlibmicroemu_1_1internal_1_1_bit_manip.html#a53aa94a3acff11d47e1af8b90ebc37a6',1,'libmicroemu::internal::BitManip']]],
  ['extractbits2r_30',['ExtractBits2R',['../classlibmicroemu_1_1internal_1_1_bit_manip.html#a2c72c88ad7c411b5bdaa257b6ecdbf49',1,'libmicroemu::internal::BitManip']]],
  ['extracttype_31',['ExtractType',['../classlibmicroemu_1_1internal_1_1_bit_manip.html#a6caafbee0159edcf54c2f0e0f07a19ea',1,'libmicroemu::internal::BitManip']]]
];
