var searchData=
[
  ['rarg_0',['RArg',['../class_r_arg.html',1,'RArg&lt; T &gt;'],['../class_r_arg.html#a3a0cc5a2b09fce93626c3ca65271ebe5',1,'RArg::RArg(T reg_id)'],['../class_r_arg.html#abcad894345430ff88427ecb0e07f3e64',1,'RArg::RArg(const RArg &amp;r_src)=default'],['../class_r_arg.html#a13a5ac39cc87fe27a0e595147e7feb81',1,'RArg::RArg(RArg &amp;&amp;r_src)=default']]],
  ['rargconst_1',['RArgConst',['../class_r_arg_const.html',1,'RArgConst&lt; Rid &gt;'],['../class_r_arg_const.html#a8fbe94fd6e77c519786281e211477c3d',1,'RArgConst::RArgConst()=default'],['../class_r_arg_const.html#aece15bf8b8d392ee9a096f99091fad57',1,'RArgConst::RArgConst(const RArgConst &amp;r_src)=default'],['../class_r_arg_const.html#a07ad7fdb355cbfcdb5fb82dd6b497c93',1,'RArgConst::RArgConst(RArgConst &amp;&amp;r_src)=default']]],
  ['rawinstr_2',['RawInstr',['../structlibmicroemu_1_1_raw_instr.html',1,'libmicroemu']]],
  ['readregister_3',['ReadRegister',['../classlibmicroemu_1_1internal_1_1_reg_accessor.html#a2dce973a0601e2308375847911cfc552',1,'libmicroemu::internal::RegAccessor::ReadRegister()'],['../classlibmicroemu_1_1internal_1_1_special_reg_accessor.html#a8c47c060680dbf4276edbc63d9e43671',1,'libmicroemu::internal::SpecialRegAccessor::ReadRegister()'],['../classlibmicroemu_1_1_i_reg_accessor.html#a3aa5deb7e66507881090bf54c705fb45',1,'libmicroemu::IRegAccessor::ReadRegister()'],['../classlibmicroemu_1_1_i_special_reg_accessor.html#a0caa4eaa81e2a6eeffc82e78911d0006',1,'libmicroemu::ISpecialRegAccessor::ReadRegister()']]],
  ['readresult_4',['ReadResult',['../structlibmicroemu_1_1internal_1_1_read_result.html',1,'libmicroemu::internal']]],
  ['regaccessor_5',['RegAccessor',['../classlibmicroemu_1_1internal_1_1_reg_accessor.html',1,'libmicroemu::internal::RegAccessor&lt; TProcessorStates, TRegOps, TSpecRegOps &gt;'],['../classlibmicroemu_1_1internal_1_1_reg_accessor.html#ac2f1b8b44f8161f008e9da5c6cd2dc14',1,'libmicroemu::internal::RegAccessor::RegAccessor(PState &amp;pstates)'],['../classlibmicroemu_1_1internal_1_1_reg_accessor.html#ac3ed55be7681ab77cb5630d0dcf1c76c',1,'libmicroemu::internal::RegAccessor::RegAccessor(const RegAccessor &amp;)=default'],['../classlibmicroemu_1_1internal_1_1_reg_accessor.html#a4695f7dac1a9efe15b9f4f5dcffafb4c',1,'libmicroemu::internal::RegAccessor::RegAccessor(RegAccessor &amp;&amp;)=default']]],
  ['registeraccessbfar_6',['RegisterAccessBfar',['../classlibmicroemu_01_1_1internal_1_1_sys_ctrl_block_1_1_register_access_bfar.html',1,'libmicroemu ::internal::SysCtrlBlock']]],
  ['registeraccesscalib_7',['RegisterAccessCalib',['../classlibmicroemu_01_1_1internal_1_1_sys_tick_1_1_register_access_calib.html',1,'libmicroemu ::internal::SysTick']]],
  ['registeraccessccr_8',['RegisterAccessCcr',['../classlibmicroemu_01_1_1internal_1_1_sys_ctrl_block_1_1_register_access_ccr.html',1,'libmicroemu ::internal::SysCtrlBlock']]],
  ['registeraccesscfsr_9',['RegisterAccessCfsr',['../classlibmicroemu_01_1_1internal_1_1_sys_ctrl_block_1_1_register_access_cfsr.html',1,'libmicroemu ::internal::SysCtrlBlock']]],
  ['registeraccesscsr_10',['RegisterAccessCsr',['../classlibmicroemu_01_1_1internal_1_1_sys_tick_1_1_register_access_csr.html',1,'libmicroemu ::internal::SysTick']]],
  ['registeraccesscvr_11',['RegisterAccessCvr',['../classlibmicroemu_01_1_1internal_1_1_sys_tick_1_1_register_access_cvr.html',1,'libmicroemu ::internal::SysTick']]],
  ['registeraccessrvr_12',['RegisterAccessRvr',['../classlibmicroemu_01_1_1internal_1_1_sys_tick_1_1_register_access_rvr.html',1,'libmicroemu ::internal::SysTick']]],
  ['registerid_13',['RegisterId',['../namespacelibmicroemu.html#aae4aa07185daf886d479bcaefc5fb94e',1,'libmicroemu']]],
  ['registeroffsets_14',['RegisterOffsets',['../structlibmicroemu_1_1_register_offsets.html',1,'libmicroemu']]],
  ['regops_15',['RegOps',['../classlibmicroemu_1_1internal_1_1_reg_ops.html',1,'libmicroemu::internal']]],
  ['relativeadrbuilder_16',['RelativeAdrBuilder',['../classlibmicroemu_1_1internal_1_1_relative_adr_builder.html',1,'libmicroemu::internal']]],
  ['releases_17',['Precompiled Libraries and Releases',['../index.html#autotoc_md7',1,'']]],
  ['result_18',['Result',['../structlibmicroemu_1_1_result.html',1,'libmicroemu']]],
  ['result_3c_20void_20_3e_19',['Result&lt; void &gt;',['../structlibmicroemu_1_1_result_3_01void_01_4.html',1,'libmicroemu']]],
  ['results_20',['Performance Results',['../index.html#autotoc_md11',1,'']]],
  ['roadmap_21',['Roadmap',['../index.html#autotoc_md3',1,'']]],
  ['ror_5fc_5fresults_22',['ROR_C_Results',['../structlibmicroemu_1_1internal_1_1_alu_1_1_r_o_r___c___results.html',1,'libmicroemu::internal::Alu']]],
  ['rrx1op_23',['Rrx1Op',['../classlibmicroemu_1_1internal_1_1_rrx1_op.html',1,'libmicroemu::internal']]],
  ['rsb1immop_24',['Rsb1ImmOp',['../classlibmicroemu_1_1internal_1_1_rsb1_imm_op.html',1,'libmicroemu::internal']]],
  ['rsb2shiftop_25',['Rsb2ShiftOp',['../classlibmicroemu_1_1internal_1_1_rsb2_shift_op.html',1,'libmicroemu::internal']]],
  ['running_20the_20emulator_26',['Running the Emulator',['../index.html#autotoc_md6',1,'']]],
  ['rxr_5fc_5fresults_27',['RXR_C_Results',['../structlibmicroemu_1_1internal_1_1_alu_1_1_r_x_r___c___results.html',1,'libmicroemu::internal::Alu']]]
];
