var searchData=
[
  ['machine_0',['Machine',['../classlibmicroemu_1_1_machine.html',1,'libmicroemu::Machine'],['../classlibmicroemu_1_1_machine.html#ab37539355382c146a78a76720dc6e042',1,'libmicroemu::Machine::Machine()']]],
  ['machine_2eh_1',['machine.h',['../machine_8h.html',1,'']]],
  ['make_5fsigned_5ftype_2',['make_signed_type',['../structlibmicroemu_1_1internal_1_1make__signed__type.html',1,'libmicroemu::internal']]],
  ['make_5fsigned_5ftype_3c_20u16_20_3e_3',['make_signed_type&lt; u16 &gt;',['../structlibmicroemu_1_1internal_1_1make__signed__type_3_01u16_01_4.html',1,'libmicroemu::internal']]],
  ['make_5fsigned_5ftype_3c_20u32_20_3e_4',['make_signed_type&lt; u32 &gt;',['../structlibmicroemu_1_1internal_1_1make__signed__type_3_01u32_01_4.html',1,'libmicroemu::internal']]],
  ['make_5fsigned_5ftype_3c_20u64_20_3e_5',['make_signed_type&lt; u64 &gt;',['../structlibmicroemu_1_1internal_1_1make__signed__type_3_01u64_01_4.html',1,'libmicroemu::internal']]],
  ['make_5fsigned_5ftype_3c_20u8_20_3e_6',['make_signed_type&lt; u8 &gt;',['../structlibmicroemu_1_1internal_1_1make__signed__type_3_01u8_01_4.html',1,'libmicroemu::internal']]],
  ['management_7',['Error Management',['../manual.html#autotoc_md19',1,'']]],
  ['manual_20for_20libmicroemu_8',['Programmer&apos;s Manual for `libmicroemu`',['../manual.html',1,'']]],
  ['memmapaccesspoint_9',['MemMapAccessPoint',['../classlibmicroemu_1_1internal_1_1_mem_map_access_point.html',1,'libmicroemu::internal']]],
  ['memmaprw_10',['MemMapRw',['../classlibmicroemu_1_1internal_1_1_mem_map_rw.html',1,'libmicroemu::internal::MemMapRw&lt; Id, VadrOffset, VadrRange, TCpuAccessor, TExceptionTrigger, TLogger, TPeripherals &gt;'],['../classlibmicroemu_1_1internal_1_1_mem_map_rw.html#afc835a34125edb73682972d32194caee',1,'libmicroemu::internal::MemMapRw::MemMapRw()=default'],['../classlibmicroemu_1_1internal_1_1_mem_map_rw.html#a73342ab43aa4a18d2cb861f2b7443d4d',1,'libmicroemu::internal::MemMapRw::MemMapRw(const MemMapRw &amp;r_src)=default'],['../classlibmicroemu_1_1internal_1_1_mem_map_rw.html#ac3ed178210088a54dea0386c4d8e6acd',1,'libmicroemu::internal::MemMapRw::MemMapRw(MemMapRw &amp;&amp;r_src)=default']]],
  ['memmaprw_3c_203u_2c_200xe0000000u_2c_200xffffu_2c_20cpuaccessor_2c_20exceptiontrigger_2c_20staticlogger_2c_20sysctrlblock_2c_20systick_20_3e_11',['MemMapRw&lt; 3U, 0xE0000000U, 0xFFFFU, CpuAccessor, ExceptionTrigger, StaticLogger, SysCtrlBlock, SysTick &gt;',['../classlibmicroemu_1_1internal_1_1_mem_map_rw.html',1,'libmicroemu::internal']]],
  ['memory_20setup_12',['Step 1: Memory Setup',['../manual.html#autotoc_md26',1,'']]],
  ['memory_5fviewer_2eh_13',['memory_viewer.h',['../memory__viewer_8h.html',1,'']]],
  ['memoryhelpers_14',['MemoryHelpers',['../classlibmicroemu_1_1internal_1_1_memory_helpers.html',1,'libmicroemu::internal']]],
  ['memoryviewer_15',['MemoryViewer',['../classlibmicroemu_1_1internal_1_1_memory_viewer.html',1,'libmicroemu::internal']]],
  ['memro_16',['MemRo',['../classlibmicroemu_01_1_1internal_1_1_mem_ro.html',1,'libmicroemu ::internal::MemRo&lt; Id, TCpuAccessor, TEndianessC &gt;'],['../classlibmicroemu_01_1_1internal_1_1_mem_ro.html#a9b169b53861c599386a5f5cacb3f8d7d',1,'libmicroemu ::internal::MemRo::MemRo(const u8 *const buf, const me_size_t buf_size, const me_adr_t vadr_offset)'],['../classlibmicroemu_01_1_1internal_1_1_mem_ro.html#a6fd02f5deeecd435186c77e033ccccf6',1,'libmicroemu ::internal::MemRo::MemRo(const MemRo &amp;r_src)=default'],['../classlibmicroemu_01_1_1internal_1_1_mem_ro.html#a9c84b34eb581b27c48965b506bcac7a2',1,'libmicroemu ::internal::MemRo::MemRo(MemRo &amp;&amp;r_src)=default']]],
  ['memrw_17',['MemRw',['../classlibmicroemu_1_1internal_1_1_mem_rw.html',1,'libmicroemu::internal::MemRw&lt; Id, TCpuAccessor, TEndianessC &gt;'],['../classlibmicroemu_1_1internal_1_1_mem_rw.html#adc1ad112d71daa3e2c484c1da31ae054',1,'libmicroemu::internal::MemRw::MemRw(u8 *const buf, const me_size_t buf_size, const me_adr_t vadr_offset)'],['../classlibmicroemu_1_1internal_1_1_mem_rw.html#ae7991ae6065198f7d54d9da4cdc91da1',1,'libmicroemu::internal::MemRw::MemRw(const MemRw &amp;r_src)=default'],['../classlibmicroemu_1_1internal_1_1_mem_rw.html#ac1372e952bd20e3d48ae99d1dbd62b37',1,'libmicroemu::internal::MemRw::MemRw(MemRw &amp;&amp;r_src)=default']]],
  ['memrw_3c_201u_2c_20cpuaccessor_2c_20endconv_20_3e_18',['MemRw&lt; 1U, CpuAccessor, EndConv &gt;',['../classlibmicroemu_1_1internal_1_1_mem_rw.html',1,'libmicroemu::internal']]],
  ['memrwoptional_19',['MemRwOptional',['../classlibmicroemu_1_1internal_1_1_mem_rw_optional.html',1,'libmicroemu::internal::MemRwOptional&lt; Id, TCpuAccessor, TEndianessC &gt;'],['../classlibmicroemu_1_1internal_1_1_mem_rw_optional.html#af1fdbea293f716f2a4b6211e17119e1f',1,'libmicroemu::internal::MemRwOptional::MemRwOptional(u8 *const buf, const me_size_t buf_size, const me_adr_t vadr_offset)'],['../classlibmicroemu_1_1internal_1_1_mem_rw_optional.html#abe56de797d28039cf7957cbc4f8fc449',1,'libmicroemu::internal::MemRwOptional::MemRwOptional(const MemRwOptional &amp;r_src)=default'],['../classlibmicroemu_1_1internal_1_1_mem_rw_optional.html#ac0687756cd292220db76e0e7b1f2b3d4',1,'libmicroemu::internal::MemRwOptional::MemRwOptional(MemRwOptional &amp;&amp;r_src)=default']]],
  ['memrwoptional_3c_202u_2c_20cpuaccessor_2c_20endconv_20_3e_20',['MemRwOptional&lt; 2U, CpuAccessor, EndConv &gt;',['../classlibmicroemu_1_1internal_1_1_mem_rw_optional.html',1,'libmicroemu::internal']]],
  ['microcontroller_20emulator_20library_21',['ARM Microcontroller Emulator Library',['../index.html',1,'']]],
  ['mla3op_22',['Mla3Op',['../classlibmicroemu_1_1internal_1_1_mla3_op.html',1,'libmicroemu::internal']]],
  ['mls3op_23',['Mls3Op',['../classlibmicroemu_1_1internal_1_1_mls3_op.html',1,'libmicroemu::internal']]],
  ['mnemonicbuilder_24',['MnemonicBuilder',['../classlibmicroemu_1_1internal_1_1_mnemonic_builder.html',1,'libmicroemu::internal']]],
  ['mnemonicbuilderbinary64bitinstr_25',['MnemonicBuilderBinary64bitInstr',['../classlibmicroemu_1_1internal_1_1_mnemonic_builder_binary64bit_instr.html',1,'libmicroemu::internal']]],
  ['mnemonicbuilderbinaryinstr_26',['MnemonicBuilderBinaryInstr',['../classlibmicroemu_1_1internal_1_1_mnemonic_builder_binary_instr.html',1,'libmicroemu::internal']]],
  ['mnemonicbuilderbinaryinstrwithimm_27',['MnemonicBuilderBinaryInstrWithImm',['../classlibmicroemu_1_1internal_1_1_mnemonic_builder_binary_instr_with_imm.html',1,'libmicroemu::internal']]],
  ['mnemonicbuilderbinaryinstrwithimmcarry_28',['MnemonicBuilderBinaryInstrWithImmCarry',['../classlibmicroemu_1_1internal_1_1_mnemonic_builder_binary_instr_with_imm_carry.html',1,'libmicroemu::internal']]],
  ['mnemonicbuilderbinaryinstrwithrotation_29',['MnemonicBuilderBinaryInstrWithRotation',['../classlibmicroemu_1_1internal_1_1_mnemonic_builder_binary_instr_with_rotation.html',1,'libmicroemu::internal']]],
  ['mnemonicbuilderbinaryinstrwithshift_30',['MnemonicBuilderBinaryInstrWithShift',['../classlibmicroemu_1_1internal_1_1_mnemonic_builder_binary_instr_with_shift.html',1,'libmicroemu::internal']]],
  ['mnemonicbuilderbinaryloadstoreinstrwithimm_31',['MnemonicBuilderBinaryLoadStoreInstrWithImm',['../classlibmicroemu_1_1internal_1_1_mnemonic_builder_binary_load_store_instr_with_imm.html',1,'libmicroemu::internal']]],
  ['mnemonicbuilderbinarynullinstr_32',['MnemonicBuilderBinaryNullInstr',['../classlibmicroemu_1_1internal_1_1_mnemonic_builder_binary_null_instr.html',1,'libmicroemu::internal']]],
  ['mnemonicbuilderbinarynullinstrwithimm_33',['MnemonicBuilderBinaryNullInstrWithImm',['../classlibmicroemu_1_1internal_1_1_mnemonic_builder_binary_null_instr_with_imm.html',1,'libmicroemu::internal']]],
  ['mnemonicbuilderbinarynullinstrwithimmcarry_34',['MnemonicBuilderBinaryNullInstrWithImmCarry',['../classlibmicroemu_1_1internal_1_1_mnemonic_builder_binary_null_instr_with_imm_carry.html',1,'libmicroemu::internal']]],
  ['mnemonicbuildercontext_35',['MnemonicBuilderContext',['../structlibmicroemu_1_1internal_1_1_mnemonic_builder_context.html',1,'libmicroemu::internal']]],
  ['mnemonicbuildernullaryinstr_36',['MnemonicBuilderNullaryInstr',['../classlibmicroemu_1_1internal_1_1_mnemonic_builder_nullary_instr.html',1,'libmicroemu::internal']]],
  ['mnemonicbuilderspecialinstr_37',['MnemonicBuilderSpecialInstr',['../classlibmicroemu_1_1internal_1_1_mnemonic_builder_special_instr.html',1,'libmicroemu::internal']]],
  ['mnemonicbuilderternaryinstr_38',['MnemonicBuilderTernaryInstr',['../classlibmicroemu_1_1internal_1_1_mnemonic_builder_ternary_instr.html',1,'libmicroemu::internal']]],
  ['mnemonicbuilderternaryinstrwithshift_39',['MnemonicBuilderTernaryInstrWithShift',['../classlibmicroemu_1_1internal_1_1_mnemonic_builder_ternary_instr_with_shift.html',1,'libmicroemu::internal']]],
  ['mnemonicbuilderternaryloadstoreinstrwithimm_40',['MnemonicBuilderTernaryLoadStoreInstrWithImm',['../classlibmicroemu_1_1internal_1_1_mnemonic_builder_ternary_load_store_instr_with_imm.html',1,'libmicroemu::internal']]],
  ['mnemonicbuilderternaryloadstoreinstrwithshift_41',['MnemonicBuilderTernaryLoadStoreInstrWithShift',['../classlibmicroemu_1_1internal_1_1_mnemonic_builder_ternary_load_store_instr_with_shift.html',1,'libmicroemu::internal']]],
  ['mnemonicbuilderternarynullinstrwithshift_42',['MnemonicBuilderTernaryNullInstrWithShift',['../classlibmicroemu_1_1internal_1_1_mnemonic_builder_ternary_null_instr_with_shift.html',1,'libmicroemu::internal']]],
  ['mnemonicbuilderunarybranchinstr_43',['MnemonicBuilderUnaryBranchInstr',['../classlibmicroemu_1_1internal_1_1_mnemonic_builder_unary_branch_instr.html',1,'libmicroemu::internal']]],
  ['mnemonicbuilderunarybranchinstrwithimm_44',['MnemonicBuilderUnaryBranchInstrWithImm',['../classlibmicroemu_1_1internal_1_1_mnemonic_builder_unary_branch_instr_with_imm.html',1,'libmicroemu::internal']]],
  ['mnemonicbuilderunaryinstr_45',['MnemonicBuilderUnaryInstr',['../classlibmicroemu_1_1internal_1_1_mnemonic_builder_unary_instr.html',1,'libmicroemu::internal']]],
  ['mnemonicbuilderunaryinstrwithimmcarry_46',['MnemonicBuilderUnaryInstrWithImmCarry',['../classlibmicroemu_1_1internal_1_1_mnemonic_builder_unary_instr_with_imm_carry.html',1,'libmicroemu::internal']]],
  ['mnemonicbuilderunarynullinstrwithimm_47',['MnemonicBuilderUnaryNullInstrWithImm',['../classlibmicroemu_1_1internal_1_1_mnemonic_builder_unary_null_instr_with_imm.html',1,'libmicroemu::internal']]],
  ['mnemonicbuildervariadicloadstoreinstr_48',['MnemonicBuilderVariadicLoadStoreInstr',['../classlibmicroemu_1_1internal_1_1_mnemonic_builder_variadic_load_store_instr.html',1,'libmicroemu::internal']]],
  ['mov1op_49',['Mov1Op',['../classlibmicroemu_1_1internal_1_1_mov1_op.html',1,'libmicroemu::internal']]],
  ['movimmcarryop_50',['MovImmCarryOp',['../classlibmicroemu_1_1internal_1_1_mov_imm_carry_op.html',1,'libmicroemu::internal']]],
  ['mrs_51',['Mrs',['../classlibmicroemu_1_1internal_1_1_special_instr.html#adb7341634f662e44503468b76521bf3b',1,'libmicroemu::internal::SpecialInstr']]],
  ['msr_52',['Msr',['../classlibmicroemu_1_1internal_1_1_special_instr.html#a4742eb8ced2cf0831b603917ad774e54',1,'libmicroemu::internal::SpecialInstr']]],
  ['mul2op_53',['Mul2Op',['../classlibmicroemu_1_1internal_1_1_mul2_op.html',1,'libmicroemu::internal']]],
  ['mvn1shiftop_54',['Mvn1ShiftOp',['../classlibmicroemu_1_1internal_1_1_mvn1_shift_op.html',1,'libmicroemu::internal']]],
  ['mvnimmcarryop_55',['MvnImmCarryOp',['../classlibmicroemu_1_1internal_1_1_mvn_imm_carry_op.html',1,'libmicroemu::internal']]]
];
