var searchData=
[
  ['sbc1immop_0',['Sbc1ImmOp',['../classmicroemu_1_1internal_1_1_sbc1_imm_op.html',1,'microemu::internal']]],
  ['sbc2shiftop_1',['Sbc2ShiftOp',['../classmicroemu_1_1internal_1_1_sbc2_shift_op.html',1,'microemu::internal']]],
  ['sdiv2op_2',['SDiv2Op',['../classmicroemu_1_1internal_1_1_s_div2_op.html',1,'microemu::internal']]],
  ['segmentiterator_3',['SegmentIterator',['../classmicroemu_1_1internal_1_1_elf_reader_1_1_segment_iterator.html',1,'microemu::internal::ElfReader']]],
  ['semihosting_4',['Semihosting',['../classmicroemu_1_1internal_1_1_semihosting.html',1,'microemu::internal::Semihosting&lt; TProcessorStates, TBus, TRegOps, TSpecRegOps, TLogger &gt;'],['../classmicroemu_1_1internal_1_1_semihosting.html#a34d0cce9a14ffc0d8abec3e0da204908',1,'microemu::internal::Semihosting::Semihosting(TProcessorStates &amp;pstates, TBus bus)']]],
  ['semihostresult_5',['SemihostResult',['../structmicroemu_1_1internal_1_1_semihosting_1_1_semihost_result.html',1,'microemu::internal::Semihosting']]],
  ['setflashsegment_6',['SetFlashSegment',['../classmicroemu_1_1_micro_emu.html#ae2a17a7d476464b29cfe70993766d2de',1,'microemu::MicroEmu']]],
  ['setram1segment_7',['SetRam1Segment',['../classmicroemu_1_1_micro_emu.html#ab11bc56d76ba13f97b816b251ba1cc6f',1,'microemu::MicroEmu']]],
  ['setram2segment_8',['SetRam2Segment',['../classmicroemu_1_1_micro_emu.html#a0745bd65ef4c35ca698d73d2f23c4f16',1,'microemu::MicroEmu']]],
  ['shiftcres_9',['ShiftCRes',['../structmicroemu_1_1internal_1_1_alu_1_1_shift_c_res.html',1,'microemu::internal::Alu']]],
  ['signextend_10',['SignExtend',['../classmicroemu_1_1internal_1_1_bit_manip.html#a7b94f1d68735b5ce767663e4f3bce4e9',1,'microemu::internal::BitManip']]],
  ['singleexceptionstate_11',['SingleExceptionState',['../structmicroemu_1_1_single_exception_state.html',1,'microemu']]],
  ['slice1r_12',['Slice1R',['../classmicroemu_1_1internal_1_1_bit_manip.html#ad367ed7c5078eaa4c682914ab11c8817',1,'microemu::internal::BitManip']]],
  ['slice2r_13',['Slice2R',['../classmicroemu_1_1internal_1_1_bit_manip.html#aa511254ec419ae9da4dd74e7f866d99a',1,'microemu::internal::BitManip']]],
  ['smull_14',['Smull',['../classmicroemu_1_1internal_1_1_special_instr.html#aca3778ff8816face0bd46573b56b607f',1,'microemu::internal::SpecialInstr']]],
  ['special_5fregister_5fid_2eh_15',['special_register_id.h',['../special__register__id_8h.html',1,'']]],
  ['specialinstr_16',['SpecialInstr',['../classmicroemu_1_1internal_1_1_special_instr.html',1,'microemu::internal']]],
  ['specialregaccess_17',['SpecialRegAccess',['../classmicroemu_1_1internal_1_1_special_reg_access.html',1,'microemu::internal::SpecialRegAccess&lt; TProcessorStates, TSpecRegOps &gt;'],['../classmicroemu_1_1internal_1_1_special_reg_access.html#a7457c1554ae8e8705b68f5fb8ec83840',1,'microemu::internal::SpecialRegAccess::SpecialRegAccess(PState &amp;pstates)'],['../classmicroemu_1_1internal_1_1_special_reg_access.html#a8fe7439a3e8b7c97fb721328161169eb',1,'microemu::internal::SpecialRegAccess::SpecialRegAccess(const SpecialRegAccess &amp;)=default'],['../classmicroemu_1_1internal_1_1_special_reg_access.html#a131a8e07e0fa645bf1e333625b8ff843',1,'microemu::internal::SpecialRegAccess::SpecialRegAccess(SpecialRegAccess &amp;&amp;)=default']]],
  ['specialregisterid_18',['SpecialRegisterId',['../namespacemicroemu.html#ac3dbeb54409eb0881b188bdf2ec8e854',1,'microemu']]],
  ['specregops_19',['SpecRegOps',['../classmicroemu_1_1internal_1_1_spec_reg_ops.html',1,'microemu::internal']]],
  ['started_20',['Getting Started',['../index.html#autotoc_md4',1,'']]],
  ['staticlogger_21',['StaticLogger',['../classmicroemu_1_1_static_logger.html',1,'microemu']]],
  ['status_22',['Development Status',['../index.html#autotoc_md2',1,'']]],
  ['storememexu32_23',['StoreMemExU32',['../classmicroemu_1_1internal_1_1_store_mem_ex_u32.html',1,'microemu::internal']]],
  ['storememu16_24',['StoreMemU16',['../classmicroemu_1_1internal_1_1_store_mem_u16.html',1,'microemu::internal']]],
  ['storememu32_25',['StoreMemU32',['../classmicroemu_1_1internal_1_1_store_mem_u32.html',1,'microemu::internal']]],
  ['storememu8_26',['StoreMemU8',['../classmicroemu_1_1internal_1_1_store_mem_u8.html',1,'microemu::internal']]],
  ['strbuilderbinaryinstr_27',['StrBuilderBinaryInstr',['../classmicroemu_1_1internal_1_1_str_builder_binary_instr.html',1,'microemu::internal']]],
  ['strbuilderbinaryinstrwithimm_28',['StrBuilderBinaryInstrWithImm',['../classmicroemu_1_1internal_1_1_str_builder_binary_instr_with_imm.html',1,'microemu::internal']]],
  ['strbuilderbinaryinstrwithimmcarry_29',['StrBuilderBinaryInstrWithImmCarry',['../classmicroemu_1_1internal_1_1_str_builder_binary_instr_with_imm_carry.html',1,'microemu::internal']]],
  ['strbuilderbinaryinstrwithrotation_30',['StrBuilderBinaryInstrWithRotation',['../classmicroemu_1_1internal_1_1_str_builder_binary_instr_with_rotation.html',1,'microemu::internal']]],
  ['strbuilderbinaryinstrwithshift_31',['StrBuilderBinaryInstrWithShift',['../classmicroemu_1_1internal_1_1_str_builder_binary_instr_with_shift.html',1,'microemu::internal']]],
  ['strbuilderbinaryloadstoreinstrwithimm_32',['StrBuilderBinaryLoadStoreInstrWithImm',['../classmicroemu_1_1internal_1_1_str_builder_binary_load_store_instr_with_imm.html',1,'microemu::internal']]],
  ['strbuilderbinarynullinstrwithimm_33',['StrBuilderBinaryNullInstrWithImm',['../classmicroemu_1_1internal_1_1_str_builder_binary_null_instr_with_imm.html',1,'microemu::internal']]],
  ['strbuilderbinarynullinstrwithimmcarry_34',['StrBuilderBinaryNullInstrWithImmCarry',['../classmicroemu_1_1internal_1_1_str_builder_binary_null_instr_with_imm_carry.html',1,'microemu::internal']]],
  ['strbuildernullaryinstr_35',['StrBuilderNullaryInstr',['../classmicroemu_1_1internal_1_1_str_builder_nullary_instr.html',1,'microemu::internal']]],
  ['strbuilderspecialinstr_36',['StrBuilderSpecialInstr',['../classmicroemu_1_1internal_1_1_str_builder_special_instr.html',1,'microemu::internal']]],
  ['strbuilderternaryinstr_37',['StrBuilderTernaryInstr',['../classmicroemu_1_1internal_1_1_str_builder_ternary_instr.html',1,'microemu::internal']]],
  ['strbuilderternaryinstrwithshift_38',['StrBuilderTernaryInstrWithShift',['../classmicroemu_1_1internal_1_1_str_builder_ternary_instr_with_shift.html',1,'microemu::internal']]],
  ['strbuilderternaryloadstoreinstrwithimm_39',['StrBuilderTernaryLoadStoreInstrWithImm',['../classmicroemu_1_1internal_1_1_str_builder_ternary_load_store_instr_with_imm.html',1,'microemu::internal']]],
  ['strbuilderternaryloadstoreinstrwithshift_40',['StrBuilderTernaryLoadStoreInstrWithShift',['../classmicroemu_1_1internal_1_1_str_builder_ternary_load_store_instr_with_shift.html',1,'microemu::internal']]],
  ['strbuilderternarynullinstrwithshift_41',['StrBuilderTernaryNullInstrWithShift',['../classmicroemu_1_1internal_1_1_str_builder_ternary_null_instr_with_shift.html',1,'microemu::internal']]],
  ['strbuilderunarybranchinstr_42',['StrBuilderUnaryBranchInstr',['../classmicroemu_1_1internal_1_1_str_builder_unary_branch_instr.html',1,'microemu::internal']]],
  ['strbuilderunarybranchinstrwithimm_43',['StrBuilderUnaryBranchInstrWithImm',['../classmicroemu_1_1internal_1_1_str_builder_unary_branch_instr_with_imm.html',1,'microemu::internal']]],
  ['strbuilderunaryinstr_44',['StrBuilderUnaryInstr',['../classmicroemu_1_1internal_1_1_str_builder_unary_instr.html',1,'microemu::internal']]],
  ['strbuilderunaryinstrwithimmcarry_45',['StrBuilderUnaryInstrWithImmCarry',['../classmicroemu_1_1internal_1_1_str_builder_unary_instr_with_imm_carry.html',1,'microemu::internal']]],
  ['strbuilderunarynullinstrwithimm_46',['StrBuilderUnaryNullInstrWithImm',['../classmicroemu_1_1internal_1_1_str_builder_unary_null_instr_with_imm.html',1,'microemu::internal']]],
  ['strbuildervariadicloadstoreinstr_47',['StrBuilderVariadicLoadStoreInstr',['../classmicroemu_1_1internal_1_1_str_builder_variadic_load_store_instr.html',1,'microemu::internal']]],
  ['strd_48',['Strd',['../classmicroemu_1_1internal_1_1_special_instr.html#ace522714b065c55a74e649975e102fcf',1,'microemu::internal::SpecialInstr']]],
  ['sub1immop_49',['Sub1ImmOp',['../classmicroemu_1_1internal_1_1_sub1_imm_op.html',1,'microemu::internal']]],
  ['sub2shiftop_50',['Sub2ShiftOp',['../classmicroemu_1_1internal_1_1_sub2_shift_op.html',1,'microemu::internal']]],
  ['svc_51',['Svc',['../classmicroemu_1_1internal_1_1_special_instr.html#ade6df0d454e565aef0e7a9ab2e3ee75c',1,'microemu::internal::SpecialInstr']]],
  ['sxtb1rotation_52',['Sxtb1Rotation',['../classmicroemu_1_1internal_1_1_sxtb1_rotation.html',1,'microemu::internal']]],
  ['sxth1rotation_53',['Sxth1Rotation',['../classmicroemu_1_1internal_1_1_sxth1_rotation.html',1,'microemu::internal']]],
  ['sysctrlblock_54',['SysCtrlBlock',['../classmicroemu_01_1_1internal_1_1_sys_ctrl_block.html',1,'microemu ::internal']]],
  ['sysctrlregister_55',['SysCtrlRegister',['../structmicroemu_1_1_sys_ctrl_register.html',1,'microemu']]],
  ['systick_56',['SysTick',['../classmicroemu_01_1_1internal_1_1_sys_tick.html',1,'microemu ::internal']]],
  ['systickregister_57',['SysTickRegister',['../structmicroemu_1_1_sys_tick_register.html',1,'microemu']]]
];
