name: docs

on:
  push:
    branches:
    - cggg/update_readme
  
jobs:
  make_docs:
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Set reusable strings
      # Turn repeated input strings (such as the build output directory) into step outputs. These step outputs can be used throughout the workflow file.
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"
    - uses: actions/setup-python@v5
      with:
          python-version: '3.13'
          cache: 'pip' # caching pip dependencies
    - run: pip install -r requirements.txt
    - uses: ssciwr/doxygen-install@v1
    - name : Install Dependencies Conan
      run: | 
        conan profile detect
        conan install . -pr ${{ github.workspace }}/profiles/Doxygen-only --build=missing 
    - name: CMake configuration
      run: |
            cmake -B ${{github.workspace}}/build/Release --preset conan-release
    - name: Build docs
      run: |
            cmake --build ${{github.workspace}}/build/Release -t docs
    - uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir:  ${{github.workspace}}/build/docs/html
