name: tests

on:
  push:
    branches:
    - main
    tags-ignore:
    - 'v*'
  pull_request:
    branches:
    - main
  
jobs:
  do_tests:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Set reusable strings
      # Turn repeated input strings (such as the build output directory) into step outputs. These step outputs can be used throughout the workflow file.
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build/Release" >> "$GITHUB_OUTPUT"
    - uses: actions/setup-python@v5
      with:
          python-version: '3.13'
          cache: 'pip' # caching pip dependencies
    - run: pip install -r requirements.txt
    - name : Install Dependencies Conan
      run: | 
        conan profile detect
        conan install . -pr ${{ github.workspace }}/profiles/ubuntu-22.04-x86_64-clang-14-release --build=missing
    - name: CMake configuration
      run: |
            cmake -B ${{ steps.strings.outputs.build-output-dir }} --preset conan-release
    - name: Build
      run: |
            cmake --build ${{ steps.strings.outputs.build-output-dir }}  
    - name: Test
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: ctest --test-dir ${{ steps.strings.outputs.build-output-dir }}  
